python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/run_fold_5/ \
  --model_id MyData_Fold5 \
  --model TimesNet \
  --data custom \
  --features M \
  --seq_len 100 \
  --num_workers 0 \
  --pred_len 0 \
  --d_model 64 \
  --d_ff 64 \
  --e_layers 2 \
  --enc_in 401 \
  --c_out 401 \
  --top_k 3 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --train_epochs 10